# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    # python3 -m pip install --upgrade pip
    # pip3 install -r requirements.txt
    echo "Worked"
    echo $(Pipeline.Workspace)
  displayName: 'Install dependencies'
- task: DownloadSecureFile@1
  name: textFile
  displayName: 'Download CA certificate'
  inputs:
    secureFile: 'txt.txt'

- script: |
    echo Installing $(textFile.secureFilePath) to the trusted CA directory...
    sudo chown root:root $(textFile.secureFilePath)
    sudo chmod a+r $(textFile.secureFilePath)
    # sudo ln -s -t /etc/ssl/certs/ $(textFile.secureFilePath)
    cat $(textFile.secureFilePath)
    echo "blah"


- task: buildandreleasetask@0
  inputs:
    samplestring: 'just some input'
    fileInput: "/home/vsts/work/_temp/txt.txt"
