# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: '3.9'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    # python3 -m pip install --upgrade pip
    # pip3 install -r requirements.txt
    echo "Worked"
    echo $(Pipeline.Workspace)
    cat '$(secureFileId_db5475d4-3707-4812-8517-134a130f98b4)'
    
  displayName: 'Install dependencies'

# - task: DownloadSecureFile@1
#   name: mySecureFile
#   displayName: 'Download secure file'
#   inputs:
#     secureFile: 'txt.txt'

# - task: DownloadSecureFile@1
#   name: mySecureFile1
#   displayName: 'Download secure file'
#   inputs:
#     secureFile: 'txt1.txt'

# - task: AppdomeAPI1@0
#   inputs:
#     samplestring: 'diff input'
#     fileInput: '$(secureFileId_txt)'
# - task: AppdomeAPI@0
#   inputs:
#     samplestring: 'just input'